/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailsafepro.model.PriorityEnum;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmailValidationRequest
 */
public class EmailValidationRequestTest {
    private final EmailValidationRequest model = new EmailValidationRequest();

    /**
     * Model tests for EmailValidationRequest
     */
    @Test
    public void testEmailValidationRequest() {
        // TODO: test EmailValidationRequest
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'checkSmtp'
     */
    @Test
    public void checkSmtpTest() {
        // TODO: test checkSmtp
    }

    /**
     * Test the property 'includeRawDns'
     */
    @Test
    public void includeRawDnsTest() {
        // TODO: test includeRawDns
    }

    /**
     * Test the property 'testingMode'
     */
    @Test
    public void testingModeTest() {
        // TODO: test testingMode
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

}
