/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailsafepro.model.APIKeyMeta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * API Key list response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class APIKeyListResponse {
  public static final String SERIALIZED_NAME_KEYS = "keys";
  @SerializedName(SERIALIZED_NAME_KEYS)
  @javax.annotation.Nonnull
  private List<APIKeyMeta> keys = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "total_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  @javax.annotation.Nonnull
  private Integer totalCount;

  public static final String SERIALIZED_NAME_ACTIVE_COUNT = "active_count";
  @SerializedName(SERIALIZED_NAME_ACTIVE_COUNT)
  @javax.annotation.Nonnull
  private Integer activeCount;

  public APIKeyListResponse() {
  }

  public APIKeyListResponse keys(@javax.annotation.Nonnull List<APIKeyMeta> keys) {
    this.keys = keys;
    return this;
  }

  public APIKeyListResponse addKeysItem(APIKeyMeta keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<>();
    }
    this.keys.add(keysItem);
    return this;
  }

  /**
   * List of API keys
   * @return keys
   */
  @javax.annotation.Nonnull
  public List<APIKeyMeta> getKeys() {
    return keys;
  }

  public void setKeys(@javax.annotation.Nonnull List<APIKeyMeta> keys) {
    this.keys = keys;
  }


  public APIKeyListResponse totalCount(@javax.annotation.Nonnull Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

  /**
   * Total number of keys
   * minimum: 0
   * @return totalCount
   */
  @javax.annotation.Nonnull
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(@javax.annotation.Nonnull Integer totalCount) {
    this.totalCount = totalCount;
  }


  public APIKeyListResponse activeCount(@javax.annotation.Nonnull Integer activeCount) {
    this.activeCount = activeCount;
    return this;
  }

  /**
   * Number of active keys
   * minimum: 0
   * @return activeCount
   */
  @javax.annotation.Nonnull
  public Integer getActiveCount() {
    return activeCount;
  }

  public void setActiveCount(@javax.annotation.Nonnull Integer activeCount) {
    this.activeCount = activeCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIKeyListResponse apIKeyListResponse = (APIKeyListResponse) o;
    return Objects.equals(this.keys, apIKeyListResponse.keys) &&
        Objects.equals(this.totalCount, apIKeyListResponse.totalCount) &&
        Objects.equals(this.activeCount, apIKeyListResponse.activeCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keys, totalCount, activeCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIKeyListResponse {\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    activeCount: ").append(toIndentedString(activeCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("keys", "total_count", "active_count"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("keys", "total_count", "active_count"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to APIKeyListResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!APIKeyListResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in APIKeyListResponse is not found in the empty JSON string", APIKeyListResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!APIKeyListResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `APIKeyListResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : APIKeyListResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("keys").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `keys` to be an array in the JSON string but got `%s`", jsonObj.get("keys").toString()));
      }

      JsonArray jsonArraykeys = jsonObj.getAsJsonArray("keys");
      // validate the required field `keys` (array)
      for (int i = 0; i < jsonArraykeys.size(); i++) {
        APIKeyMeta.validateJsonElement(jsonArraykeys.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!APIKeyListResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'APIKeyListResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<APIKeyListResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(APIKeyListResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<APIKeyListResponse>() {
           @Override
           public void write(JsonWriter out, APIKeyListResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public APIKeyListResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of APIKeyListResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of APIKeyListResponse
   * @throws IOException if the JSON string is invalid with respect to APIKeyListResponse
   */
  public static APIKeyListResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, APIKeyListResponse.class);
  }

  /**
   * Convert an instance of APIKeyListResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

