/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * Request model for batch email validation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class BatchValidationRequest {
  public static final String SERIALIZED_NAME_EMAILS = "emails";
  @SerializedName(SERIALIZED_NAME_EMAILS)
  @javax.annotation.Nonnull
  private List<String> emails = new ArrayList<>();

  public static final String SERIALIZED_NAME_CHECK_SMTP = "check_smtp";
  @SerializedName(SERIALIZED_NAME_CHECK_SMTP)
  @javax.annotation.Nullable
  private Boolean checkSmtp = false;

  public static final String SERIALIZED_NAME_INCLUDE_RAW_DNS = "include_raw_dns";
  @SerializedName(SERIALIZED_NAME_INCLUDE_RAW_DNS)
  @javax.annotation.Nullable
  private Boolean includeRawDns = false;

  public static final String SERIALIZED_NAME_BATCH_SIZE = "batch_size";
  @SerializedName(SERIALIZED_NAME_BATCH_SIZE)
  @javax.annotation.Nullable
  private Integer batchSize = 100;

  public static final String SERIALIZED_NAME_CONCURRENT_REQUESTS = "concurrent_requests";
  @SerializedName(SERIALIZED_NAME_CONCURRENT_REQUESTS)
  @javax.annotation.Nullable
  private Integer concurrentRequests = 5;

  public BatchValidationRequest() {
  }

  public BatchValidationRequest emails(@javax.annotation.Nonnull List<String> emails) {
    this.emails = emails;
    return this;
  }

  public BatchValidationRequest addEmailsItem(String emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

  /**
   * List of email addresses to validate (can include invalid formats)
   * @return emails
   */
  @javax.annotation.Nonnull
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(@javax.annotation.Nonnull List<String> emails) {
    this.emails = emails;
  }


  public BatchValidationRequest checkSmtp(@javax.annotation.Nullable Boolean checkSmtp) {
    this.checkSmtp = checkSmtp;
    return this;
  }

  /**
   * Perform SMTP verification for all emails
   * @return checkSmtp
   */
  @javax.annotation.Nullable
  public Boolean getCheckSmtp() {
    return checkSmtp;
  }

  public void setCheckSmtp(@javax.annotation.Nullable Boolean checkSmtp) {
    this.checkSmtp = checkSmtp;
  }


  public BatchValidationRequest includeRawDns(@javax.annotation.Nullable Boolean includeRawDns) {
    this.includeRawDns = includeRawDns;
    return this;
  }

  /**
   * Include raw DNS records in responses
   * @return includeRawDns
   */
  @javax.annotation.Nullable
  public Boolean getIncludeRawDns() {
    return includeRawDns;
  }

  public void setIncludeRawDns(@javax.annotation.Nullable Boolean includeRawDns) {
    this.includeRawDns = includeRawDns;
  }


  public BatchValidationRequest batchSize(@javax.annotation.Nullable Integer batchSize) {
    this.batchSize = batchSize;
    return this;
  }

  /**
   * Number of emails to process in each batch
   * minimum: 1
   * maximum: 1000
   * @return batchSize
   */
  @javax.annotation.Nullable
  public Integer getBatchSize() {
    return batchSize;
  }

  public void setBatchSize(@javax.annotation.Nullable Integer batchSize) {
    this.batchSize = batchSize;
  }


  public BatchValidationRequest concurrentRequests(@javax.annotation.Nullable Integer concurrentRequests) {
    this.concurrentRequests = concurrentRequests;
    return this;
  }

  /**
   * Maximum concurrent validation requests
   * minimum: 1
   * maximum: 50
   * @return concurrentRequests
   */
  @javax.annotation.Nullable
  public Integer getConcurrentRequests() {
    return concurrentRequests;
  }

  public void setConcurrentRequests(@javax.annotation.Nullable Integer concurrentRequests) {
    this.concurrentRequests = concurrentRequests;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchValidationRequest batchValidationRequest = (BatchValidationRequest) o;
    return Objects.equals(this.emails, batchValidationRequest.emails) &&
        Objects.equals(this.checkSmtp, batchValidationRequest.checkSmtp) &&
        Objects.equals(this.includeRawDns, batchValidationRequest.includeRawDns) &&
        Objects.equals(this.batchSize, batchValidationRequest.batchSize) &&
        Objects.equals(this.concurrentRequests, batchValidationRequest.concurrentRequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emails, checkSmtp, includeRawDns, batchSize, concurrentRequests);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchValidationRequest {\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    checkSmtp: ").append(toIndentedString(checkSmtp)).append("\n");
    sb.append("    includeRawDns: ").append(toIndentedString(includeRawDns)).append("\n");
    sb.append("    batchSize: ").append(toIndentedString(batchSize)).append("\n");
    sb.append("    concurrentRequests: ").append(toIndentedString(concurrentRequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("emails", "check_smtp", "include_raw_dns", "batch_size", "concurrent_requests"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("emails"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchValidationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchValidationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BatchValidationRequest is not found in the empty JSON string", BatchValidationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchValidationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BatchValidationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchValidationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("emails") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("emails").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `emails` to be an array in the JSON string but got `%s`", jsonObj.get("emails").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchValidationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchValidationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchValidationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchValidationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchValidationRequest>() {
           @Override
           public void write(JsonWriter out, BatchValidationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchValidationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchValidationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchValidationRequest
   * @throws IOException if the JSON string is invalid with respect to BatchValidationRequest
   */
  public static BatchValidationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchValidationRequest.class);
  }

  /**
   * Convert an instance of BatchValidationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

