/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailsafepro.model.DNSRecordDKIM;
import com.mailsafepro.model.DNSRecordDMARC;
import com.mailsafepro.model.DNSRecordSPF;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * Comprehensive DNS information for email validation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class DNSInfo {
  public static final String SERIALIZED_NAME_SPF = "spf";
  @SerializedName(SERIALIZED_NAME_SPF)
  @javax.annotation.Nullable
  private DNSRecordSPF spf;

  public static final String SERIALIZED_NAME_DKIM = "dkim";
  @SerializedName(SERIALIZED_NAME_DKIM)
  @javax.annotation.Nullable
  private DNSRecordDKIM dkim;

  public static final String SERIALIZED_NAME_DMARC = "dmarc";
  @SerializedName(SERIALIZED_NAME_DMARC)
  @javax.annotation.Nullable
  private DNSRecordDMARC dmarc;

  public static final String SERIALIZED_NAME_MX_RECORDS = "mx_records";
  @SerializedName(SERIALIZED_NAME_MX_RECORDS)
  @javax.annotation.Nullable
  private List<String> mxRecords = new ArrayList<>();

  public static final String SERIALIZED_NAME_NS_RECORDS = "ns_records";
  @SerializedName(SERIALIZED_NAME_NS_RECORDS)
  @javax.annotation.Nullable
  private List<String> nsRecords = new ArrayList<>();

  public DNSInfo() {
  }

  public DNSInfo spf(@javax.annotation.Nullable DNSRecordSPF spf) {
    this.spf = spf;
    return this;
  }

  /**
   * Get spf
   * @return spf
   */
  @javax.annotation.Nullable
  public DNSRecordSPF getSpf() {
    return spf;
  }

  public void setSpf(@javax.annotation.Nullable DNSRecordSPF spf) {
    this.spf = spf;
  }


  public DNSInfo dkim(@javax.annotation.Nullable DNSRecordDKIM dkim) {
    this.dkim = dkim;
    return this;
  }

  /**
   * Get dkim
   * @return dkim
   */
  @javax.annotation.Nullable
  public DNSRecordDKIM getDkim() {
    return dkim;
  }

  public void setDkim(@javax.annotation.Nullable DNSRecordDKIM dkim) {
    this.dkim = dkim;
  }


  public DNSInfo dmarc(@javax.annotation.Nullable DNSRecordDMARC dmarc) {
    this.dmarc = dmarc;
    return this;
  }

  /**
   * Get dmarc
   * @return dmarc
   */
  @javax.annotation.Nullable
  public DNSRecordDMARC getDmarc() {
    return dmarc;
  }

  public void setDmarc(@javax.annotation.Nullable DNSRecordDMARC dmarc) {
    this.dmarc = dmarc;
  }


  public DNSInfo mxRecords(@javax.annotation.Nullable List<String> mxRecords) {
    this.mxRecords = mxRecords;
    return this;
  }

  public DNSInfo addMxRecordsItem(String mxRecordsItem) {
    if (this.mxRecords == null) {
      this.mxRecords = new ArrayList<>();
    }
    this.mxRecords.add(mxRecordsItem);
    return this;
  }

  /**
   * MX records
   * @return mxRecords
   */
  @javax.annotation.Nullable
  public List<String> getMxRecords() {
    return mxRecords;
  }

  public void setMxRecords(@javax.annotation.Nullable List<String> mxRecords) {
    this.mxRecords = mxRecords;
  }


  public DNSInfo nsRecords(@javax.annotation.Nullable List<String> nsRecords) {
    this.nsRecords = nsRecords;
    return this;
  }

  public DNSInfo addNsRecordsItem(String nsRecordsItem) {
    if (this.nsRecords == null) {
      this.nsRecords = new ArrayList<>();
    }
    this.nsRecords.add(nsRecordsItem);
    return this;
  }

  /**
   * Name servers
   * @return nsRecords
   */
  @javax.annotation.Nullable
  public List<String> getNsRecords() {
    return nsRecords;
  }

  public void setNsRecords(@javax.annotation.Nullable List<String> nsRecords) {
    this.nsRecords = nsRecords;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DNSInfo dnSInfo = (DNSInfo) o;
    return Objects.equals(this.spf, dnSInfo.spf) &&
        Objects.equals(this.dkim, dnSInfo.dkim) &&
        Objects.equals(this.dmarc, dnSInfo.dmarc) &&
        Objects.equals(this.mxRecords, dnSInfo.mxRecords) &&
        Objects.equals(this.nsRecords, dnSInfo.nsRecords);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(spf, dkim, dmarc, mxRecords, nsRecords);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DNSInfo {\n");
    sb.append("    spf: ").append(toIndentedString(spf)).append("\n");
    sb.append("    dkim: ").append(toIndentedString(dkim)).append("\n");
    sb.append("    dmarc: ").append(toIndentedString(dmarc)).append("\n");
    sb.append("    mxRecords: ").append(toIndentedString(mxRecords)).append("\n");
    sb.append("    nsRecords: ").append(toIndentedString(nsRecords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("spf", "dkim", "dmarc", "mx_records", "ns_records"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DNSInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DNSInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DNSInfo is not found in the empty JSON string", DNSInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DNSInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DNSInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `spf`
      if (jsonObj.get("spf") != null && !jsonObj.get("spf").isJsonNull()) {
        DNSRecordSPF.validateJsonElement(jsonObj.get("spf"));
      }
      // validate the optional field `dkim`
      if (jsonObj.get("dkim") != null && !jsonObj.get("dkim").isJsonNull()) {
        DNSRecordDKIM.validateJsonElement(jsonObj.get("dkim"));
      }
      // validate the optional field `dmarc`
      if (jsonObj.get("dmarc") != null && !jsonObj.get("dmarc").isJsonNull()) {
        DNSRecordDMARC.validateJsonElement(jsonObj.get("dmarc"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("mx_records") != null && !jsonObj.get("mx_records").isJsonNull() && !jsonObj.get("mx_records").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mx_records` to be an array in the JSON string but got `%s`", jsonObj.get("mx_records").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("ns_records") != null && !jsonObj.get("ns_records").isJsonNull() && !jsonObj.get("ns_records").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ns_records` to be an array in the JSON string but got `%s`", jsonObj.get("ns_records").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DNSInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DNSInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DNSInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DNSInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<DNSInfo>() {
           @Override
           public void write(JsonWriter out, DNSInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DNSInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DNSInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DNSInfo
   * @throws IOException if the JSON string is invalid with respect to DNSInfo
   */
  public static DNSInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DNSInfo.class);
  }

  /**
   * Convert an instance of DNSInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

