/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * JobCreateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class JobCreateRequest {
  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  @javax.annotation.Nonnull
  private String source;

  public static final String SERIALIZED_NAME_EMAILS = "emails";
  @SerializedName(SERIALIZED_NAME_EMAILS)
  @javax.annotation.Nullable
  private List<String> emails;

  public static final String SERIALIZED_NAME_FILE_TOKEN = "file_token";
  @SerializedName(SERIALIZED_NAME_FILE_TOKEN)
  @javax.annotation.Nullable
  private String fileToken;

  public static final String SERIALIZED_NAME_CHECKSMTP = "checksmtp";
  @SerializedName(SERIALIZED_NAME_CHECKSMTP)
  @javax.annotation.Nullable
  private Boolean checksmtp = false;

  public static final String SERIALIZED_NAME_INCLUDERAWDNS = "includerawdns";
  @SerializedName(SERIALIZED_NAME_INCLUDERAWDNS)
  @javax.annotation.Nullable
  private Boolean includerawdns = false;

  public static final String SERIALIZED_NAME_CALLBACK_URL = "callback_url";
  @SerializedName(SERIALIZED_NAME_CALLBACK_URL)
  @javax.annotation.Nullable
  private String callbackUrl;

  public static final String SERIALIZED_NAME_SANDBOX = "sandbox";
  @SerializedName(SERIALIZED_NAME_SANDBOX)
  @javax.annotation.Nullable
  private Boolean sandbox = false;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Object metadata;

  public JobCreateRequest() {
  }

  public JobCreateRequest source(@javax.annotation.Nonnull String source) {
    this.source = source;
    return this;
  }

  /**
   * Origen de los datos
   * @return source
   */
  @javax.annotation.Nonnull
  public String getSource() {
    return source;
  }

  public void setSource(@javax.annotation.Nonnull String source) {
    this.source = source;
  }


  public JobCreateRequest emails(@javax.annotation.Nullable List<String> emails) {
    this.emails = emails;
    return this;
  }

  public JobCreateRequest addEmailsItem(String emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

  /**
   * Get emails
   * @return emails
   */
  @javax.annotation.Nullable
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(@javax.annotation.Nullable List<String> emails) {
    this.emails = emails;
  }


  public JobCreateRequest fileToken(@javax.annotation.Nullable String fileToken) {
    this.fileToken = fileToken;
    return this;
  }

  /**
   * Get fileToken
   * @return fileToken
   */
  @javax.annotation.Nullable
  public String getFileToken() {
    return fileToken;
  }

  public void setFileToken(@javax.annotation.Nullable String fileToken) {
    this.fileToken = fileToken;
  }


  public JobCreateRequest checksmtp(@javax.annotation.Nullable Boolean checksmtp) {
    this.checksmtp = checksmtp;
    return this;
  }

  /**
   * Get checksmtp
   * @return checksmtp
   */
  @javax.annotation.Nullable
  public Boolean getChecksmtp() {
    return checksmtp;
  }

  public void setChecksmtp(@javax.annotation.Nullable Boolean checksmtp) {
    this.checksmtp = checksmtp;
  }


  public JobCreateRequest includerawdns(@javax.annotation.Nullable Boolean includerawdns) {
    this.includerawdns = includerawdns;
    return this;
  }

  /**
   * Get includerawdns
   * @return includerawdns
   */
  @javax.annotation.Nullable
  public Boolean getIncluderawdns() {
    return includerawdns;
  }

  public void setIncluderawdns(@javax.annotation.Nullable Boolean includerawdns) {
    this.includerawdns = includerawdns;
  }


  public JobCreateRequest callbackUrl(@javax.annotation.Nullable String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * Get callbackUrl
   * @return callbackUrl
   */
  @javax.annotation.Nullable
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(@javax.annotation.Nullable String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public JobCreateRequest sandbox(@javax.annotation.Nullable Boolean sandbox) {
    this.sandbox = sandbox;
    return this;
  }

  /**
   * Get sandbox
   * @return sandbox
   */
  @javax.annotation.Nullable
  public Boolean getSandbox() {
    return sandbox;
  }

  public void setSandbox(@javax.annotation.Nullable Boolean sandbox) {
    this.sandbox = sandbox;
  }


  public JobCreateRequest metadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobCreateRequest jobCreateRequest = (JobCreateRequest) o;
    return Objects.equals(this.source, jobCreateRequest.source) &&
        Objects.equals(this.emails, jobCreateRequest.emails) &&
        Objects.equals(this.fileToken, jobCreateRequest.fileToken) &&
        Objects.equals(this.checksmtp, jobCreateRequest.checksmtp) &&
        Objects.equals(this.includerawdns, jobCreateRequest.includerawdns) &&
        Objects.equals(this.callbackUrl, jobCreateRequest.callbackUrl) &&
        Objects.equals(this.sandbox, jobCreateRequest.sandbox) &&
        Objects.equals(this.metadata, jobCreateRequest.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, emails, fileToken, checksmtp, includerawdns, callbackUrl, sandbox, metadata);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobCreateRequest {\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    fileToken: ").append(toIndentedString(fileToken)).append("\n");
    sb.append("    checksmtp: ").append(toIndentedString(checksmtp)).append("\n");
    sb.append("    includerawdns: ").append(toIndentedString(includerawdns)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    sandbox: ").append(toIndentedString(sandbox)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("source", "emails", "file_token", "checksmtp", "includerawdns", "callback_url", "sandbox", "metadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("source"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobCreateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobCreateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in JobCreateRequest is not found in the empty JSON string", JobCreateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobCreateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `JobCreateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : JobCreateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("emails") != null && !jsonObj.get("emails").isJsonNull() && !jsonObj.get("emails").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `emails` to be an array in the JSON string but got `%s`", jsonObj.get("emails").toString()));
      }
      if ((jsonObj.get("file_token") != null && !jsonObj.get("file_token").isJsonNull()) && !jsonObj.get("file_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `file_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("file_token").toString()));
      }
      if ((jsonObj.get("callback_url") != null && !jsonObj.get("callback_url").isJsonNull()) && !jsonObj.get("callback_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `callback_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callback_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobCreateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobCreateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobCreateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobCreateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<JobCreateRequest>() {
           @Override
           public void write(JsonWriter out, JobCreateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobCreateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobCreateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobCreateRequest
   * @throws IOException if the JSON string is invalid with respect to JobCreateRequest
   */
  public static JobCreateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobCreateRequest.class);
  }

  /**
   * Convert an instance of JobCreateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

