/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * API Key rotation request
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class KeyRotationRequest {
  public static final String SERIALIZED_NAME_OLD_KEY = "old_key";
  @SerializedName(SERIALIZED_NAME_OLD_KEY)
  @javax.annotation.Nonnull
  private String oldKey;

  public static final String SERIALIZED_NAME_NEW_KEY = "new_key";
  @SerializedName(SERIALIZED_NAME_NEW_KEY)
  @javax.annotation.Nonnull
  private String newKey;

  public static final String SERIALIZED_NAME_GRACE_PERIOD = "grace_period";
  @SerializedName(SERIALIZED_NAME_GRACE_PERIOD)
  @javax.annotation.Nullable
  private Integer gracePeriod = 86400;

  public KeyRotationRequest() {
  }

  public KeyRotationRequest oldKey(@javax.annotation.Nonnull String oldKey) {
    this.oldKey = oldKey;
    return this;
  }

  /**
   * Current API key to rotate from
   * @return oldKey
   */
  @javax.annotation.Nonnull
  public String getOldKey() {
    return oldKey;
  }

  public void setOldKey(@javax.annotation.Nonnull String oldKey) {
    this.oldKey = oldKey;
  }


  public KeyRotationRequest newKey(@javax.annotation.Nonnull String newKey) {
    this.newKey = newKey;
    return this;
  }

  /**
   * New API key to rotate to
   * @return newKey
   */
  @javax.annotation.Nonnull
  public String getNewKey() {
    return newKey;
  }

  public void setNewKey(@javax.annotation.Nonnull String newKey) {
    this.newKey = newKey;
  }


  public KeyRotationRequest gracePeriod(@javax.annotation.Nullable Integer gracePeriod) {
    this.gracePeriod = gracePeriod;
    return this;
  }

  /**
   * Grace period in seconds (max 30 days)
   * minimum: 0
   * maximum: 2592000
   * @return gracePeriod
   */
  @javax.annotation.Nullable
  public Integer getGracePeriod() {
    return gracePeriod;
  }

  public void setGracePeriod(@javax.annotation.Nullable Integer gracePeriod) {
    this.gracePeriod = gracePeriod;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyRotationRequest keyRotationRequest = (KeyRotationRequest) o;
    return Objects.equals(this.oldKey, keyRotationRequest.oldKey) &&
        Objects.equals(this.newKey, keyRotationRequest.newKey) &&
        Objects.equals(this.gracePeriod, keyRotationRequest.gracePeriod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldKey, newKey, gracePeriod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyRotationRequest {\n");
    sb.append("    oldKey: ").append(toIndentedString(oldKey)).append("\n");
    sb.append("    newKey: ").append(toIndentedString(newKey)).append("\n");
    sb.append("    gracePeriod: ").append(toIndentedString(gracePeriod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("old_key", "new_key", "grace_period"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("old_key", "new_key"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to KeyRotationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KeyRotationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in KeyRotationRequest is not found in the empty JSON string", KeyRotationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KeyRotationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `KeyRotationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : KeyRotationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("old_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `old_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("old_key").toString()));
      }
      if (!jsonObj.get("new_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `new_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KeyRotationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KeyRotationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KeyRotationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KeyRotationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<KeyRotationRequest>() {
           @Override
           public void write(JsonWriter out, KeyRotationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KeyRotationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of KeyRotationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of KeyRotationRequest
   * @throws IOException if the JSON string is invalid with respect to KeyRotationRequest
   */
  public static KeyRotationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KeyRotationRequest.class);
  }

  /**
   * Convert an instance of KeyRotationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

