/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiCallback;
import com.mailsafepro.ApiClient;
import com.mailsafepro.ApiException;
import com.mailsafepro.ApiResponse;
import com.mailsafepro.Configuration;
import com.mailsafepro.Pair;
import com.mailsafepro.ProgressRequestBody;
import com.mailsafepro.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mailsafepro.model.BatchEmailResponse;
import com.mailsafepro.model.BatchValidationRequest;
import com.mailsafepro.model.EmailValidationRequest;
import java.io.File;
import com.mailsafepro.model.HTTPValidationError;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EmailValidationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public EmailValidationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EmailValidationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for batchValidateEmailsValidateBatchPost
     * @param batchValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Batch validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid batch request </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> Batch too large </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchValidateEmailsValidateBatchPostCall(@javax.annotation.Nonnull BatchValidationRequest batchValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = batchValidationRequest;

        // create path and map variables
        String localVarPath = "/validate/batch";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call batchValidateEmailsValidateBatchPostValidateBeforeCall(@javax.annotation.Nonnull BatchValidationRequest batchValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'batchValidationRequest' is set
        if (batchValidationRequest == null) {
            throw new ApiException("Missing the required parameter 'batchValidationRequest' when calling batchValidateEmailsValidateBatchPost(Async)");
        }

        return batchValidateEmailsValidateBatchPostCall(batchValidationRequest, xAPIKey, authorization, _callback);

    }

    /**
     * Batch Email Validation
     * Valida múltiples direcciones de email en una sola solicitud.
     * @param batchValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return BatchEmailResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Batch validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid batch request </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> Batch too large </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public BatchEmailResponse batchValidateEmailsValidateBatchPost(@javax.annotation.Nonnull BatchValidationRequest batchValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<BatchEmailResponse> localVarResp = batchValidateEmailsValidateBatchPostWithHttpInfo(batchValidationRequest, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Batch Email Validation
     * Valida múltiples direcciones de email en una sola solicitud.
     * @param batchValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;BatchEmailResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Batch validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid batch request </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> Batch too large </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BatchEmailResponse> batchValidateEmailsValidateBatchPostWithHttpInfo(@javax.annotation.Nonnull BatchValidationRequest batchValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = batchValidateEmailsValidateBatchPostValidateBeforeCall(batchValidationRequest, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<BatchEmailResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Batch Email Validation (asynchronously)
     * Valida múltiples direcciones de email en una sola solicitud.
     * @param batchValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Batch validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid batch request </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> Batch too large </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchValidateEmailsValidateBatchPostAsync(@javax.annotation.Nonnull BatchValidationRequest batchValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<BatchEmailResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = batchValidateEmailsValidateBatchPostValidateBeforeCall(batchValidationRequest, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<BatchEmailResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for batchValidateUploadValidateBatchUploadPost
     * @param _file  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param column  (optional)
     * @param includeRawDns  (optional, default to false)
     * @param checkSmtp  (optional, default to false)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid file or parameters </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> File too large </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> Unsupported file type </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchValidateUploadValidateBatchUploadPostCall(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String column, @javax.annotation.Nullable Boolean includeRawDns, @javax.annotation.Nullable Boolean checkSmtp, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/validate/batch/upload";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (_file != null) {
            localVarFormParams.put("file", _file);
        }

        if (column != null) {
            localVarFormParams.put("column", column);
        }

        if (includeRawDns != null) {
            localVarFormParams.put("include_raw_dns", includeRawDns);
        }

        if (checkSmtp != null) {
            localVarFormParams.put("check_smtp", checkSmtp);
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call batchValidateUploadValidateBatchUploadPostValidateBeforeCall(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String column, @javax.annotation.Nullable Boolean includeRawDns, @javax.annotation.Nullable Boolean checkSmtp, final ApiCallback _callback) throws ApiException {
        // verify the required parameter '_file' is set
        if (_file == null) {
            throw new ApiException("Missing the required parameter '_file' when calling batchValidateUploadValidateBatchUploadPost(Async)");
        }

        return batchValidateUploadValidateBatchUploadPostCall(_file, xAPIKey, authorization, column, includeRawDns, checkSmtp, _callback);

    }

    /**
     * Batch Email Validation via File Upload
     * 
     * @param _file  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param column  (optional)
     * @param includeRawDns  (optional, default to false)
     * @param checkSmtp  (optional, default to false)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid file or parameters </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> File too large </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> Unsupported file type </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object batchValidateUploadValidateBatchUploadPost(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String column, @javax.annotation.Nullable Boolean includeRawDns, @javax.annotation.Nullable Boolean checkSmtp) throws ApiException {
        ApiResponse<Object> localVarResp = batchValidateUploadValidateBatchUploadPostWithHttpInfo(_file, xAPIKey, authorization, column, includeRawDns, checkSmtp);
        return localVarResp.getData();
    }

    /**
     * Batch Email Validation via File Upload
     * 
     * @param _file  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param column  (optional)
     * @param includeRawDns  (optional, default to false)
     * @param checkSmtp  (optional, default to false)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid file or parameters </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> File too large </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> Unsupported file type </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> batchValidateUploadValidateBatchUploadPostWithHttpInfo(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String column, @javax.annotation.Nullable Boolean includeRawDns, @javax.annotation.Nullable Boolean checkSmtp) throws ApiException {
        okhttp3.Call localVarCall = batchValidateUploadValidateBatchUploadPostValidateBeforeCall(_file, xAPIKey, authorization, column, includeRawDns, checkSmtp, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Batch Email Validation via File Upload (asynchronously)
     * 
     * @param _file  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param column  (optional)
     * @param includeRawDns  (optional, default to false)
     * @param checkSmtp  (optional, default to false)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation completed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid file or parameters </td><td>  -  </td></tr>
        <tr><td> 413 </td><td> File too large </td><td>  -  </td></tr>
        <tr><td> 415 </td><td> Unsupported file type </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Rate limit exceeded </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call batchValidateUploadValidateBatchUploadPostAsync(@javax.annotation.Nonnull File _file, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String column, @javax.annotation.Nullable Boolean includeRawDns, @javax.annotation.Nullable Boolean checkSmtp, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = batchValidateUploadValidateBatchUploadPostValidateBeforeCall(_file, xAPIKey, authorization, column, includeRawDns, checkSmtp, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getCacheStatsValidateStatsCacheGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCacheStatsValidateStatsCacheGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/validate/stats/cache";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCacheStatsValidateStatsCacheGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getCacheStatsValidateStatsCacheGetCall(_callback);

    }

    /**
     * Get Cache Stats
     * Obtiene estadísticas de cache del sistema.
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public Object getCacheStatsValidateStatsCacheGet() throws ApiException {
        ApiResponse<Object> localVarResp = getCacheStatsValidateStatsCacheGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get Cache Stats
     * Obtiene estadísticas de cache del sistema.
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> getCacheStatsValidateStatsCacheGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getCacheStatsValidateStatsCacheGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Cache Stats (asynchronously)
     * Obtiene estadísticas de cache del sistema.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCacheStatsValidateStatsCacheGetAsync(final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCacheStatsValidateStatsCacheGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getUsageStatsValidateStatsUsageGet
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getUsageStatsValidateStatsUsageGetCall(@javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/validate/stats/usage";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getUsageStatsValidateStatsUsageGetValidateBeforeCall(@javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        return getUsageStatsValidateStatsUsageGetCall(xAPIKey, authorization, _callback);

    }

    /**
     * Get Usage Stats
     * Obtiene estadísticas de uso del cliente actual.
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object getUsageStatsValidateStatsUsageGet(@javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = getUsageStatsValidateStatsUsageGetWithHttpInfo(xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Get Usage Stats
     * Obtiene estadísticas de uso del cliente actual.
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> getUsageStatsValidateStatsUsageGetWithHttpInfo(@javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getUsageStatsValidateStatsUsageGetValidateBeforeCall(xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Usage Stats (asynchronously)
     * Obtiene estadísticas de uso del cliente actual.
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getUsageStatsValidateStatsUsageGetAsync(@javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getUsageStatsValidateStatsUsageGetValidateBeforeCall(xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for healthCheckValidateHealthGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call healthCheckValidateHealthGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/validate/health";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call healthCheckValidateHealthGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return healthCheckValidateHealthGetCall(_callback);

    }

    /**
     * Health Check
     * Health check completo del servicio de validación.
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public Object healthCheckValidateHealthGet() throws ApiException {
        ApiResponse<Object> localVarResp = healthCheckValidateHealthGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Health Check
     * Health check completo del servicio de validación.
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> healthCheckValidateHealthGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = healthCheckValidateHealthGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Health Check (asynchronously)
     * Health check completo del servicio de validación.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call healthCheckValidateHealthGetAsync(final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = healthCheckValidateHealthGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for healthCheckValidateHealthHead
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call healthCheckValidateHealthHeadCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/validate/health";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "HEAD", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call healthCheckValidateHealthHeadValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return healthCheckValidateHealthHeadCall(_callback);

    }

    /**
     * Health Check
     * Health check completo del servicio de validación.
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public Object healthCheckValidateHealthHead() throws ApiException {
        ApiResponse<Object> localVarResp = healthCheckValidateHealthHeadWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Health Check
     * Health check completo del servicio de validación.
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> healthCheckValidateHealthHeadWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = healthCheckValidateHealthHeadValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Health Check (asynchronously)
     * Health check completo del servicio de validación.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call healthCheckValidateHealthHeadAsync(final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = healthCheckValidateHealthHeadValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for validateEmailEndpointValidateEmailPost
     * @param emailValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validateEmailEndpointValidateEmailPostCall(@javax.annotation.Nonnull EmailValidationRequest emailValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = emailValidationRequest;

        // create path and map variables
        String localVarPath = "/validate/email";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validateEmailEndpointValidateEmailPostValidateBeforeCall(@javax.annotation.Nonnull EmailValidationRequest emailValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'emailValidationRequest' is set
        if (emailValidationRequest == null) {
            throw new ApiException("Missing the required parameter 'emailValidationRequest' when calling validateEmailEndpointValidateEmailPost(Async)");
        }

        return validateEmailEndpointValidateEmailPostCall(emailValidationRequest, xAPIKey, authorization, _callback);

    }

    /**
     * Validate Email Endpoint
     * ✅ Endpoint de validación de email con timeout y fallback robusto.  Cambios principales: - Timeout explícito por plan (FREE: 15s, PREMIUM: 45s, ENTERPRISE: 60s) - Fallback BASIC seguro si se vence - SIEMPRE retorna JSONResponse válida - client_plan en TODAS las respuestas - spam_trap_check ejecutado ANTES del timeout para estar disponible en fallback - Manejo de errores con ResponseBuilder - ✅ NUEVO: Soporte para TLD .test en testing_mode
     * @param emailValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object validateEmailEndpointValidateEmailPost(@javax.annotation.Nonnull EmailValidationRequest emailValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<Object> localVarResp = validateEmailEndpointValidateEmailPostWithHttpInfo(emailValidationRequest, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Validate Email Endpoint
     * ✅ Endpoint de validación de email con timeout y fallback robusto.  Cambios principales: - Timeout explícito por plan (FREE: 15s, PREMIUM: 45s, ENTERPRISE: 60s) - Fallback BASIC seguro si se vence - SIEMPRE retorna JSONResponse válida - client_plan en TODAS las respuestas - spam_trap_check ejecutado ANTES del timeout para estar disponible en fallback - Manejo de errores con ResponseBuilder - ✅ NUEVO: Soporte para TLD .test en testing_mode
     * @param emailValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> validateEmailEndpointValidateEmailPostWithHttpInfo(@javax.annotation.Nonnull EmailValidationRequest emailValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = validateEmailEndpointValidateEmailPostValidateBeforeCall(emailValidationRequest, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Validate Email Endpoint (asynchronously)
     * ✅ Endpoint de validación de email con timeout y fallback robusto.  Cambios principales: - Timeout explícito por plan (FREE: 15s, PREMIUM: 45s, ENTERPRISE: 60s) - Fallback BASIC seguro si se vence - SIEMPRE retorna JSONResponse válida - client_plan en TODAS las respuestas - spam_trap_check ejecutado ANTES del timeout para estar disponible en fallback - Manejo de errores con ResponseBuilder - ✅ NUEVO: Soporte para TLD .test en testing_mode
     * @param emailValidationRequest  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validateEmailEndpointValidateEmailPostAsync(@javax.annotation.Nonnull EmailValidationRequest emailValidationRequest, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = validateEmailEndpointValidateEmailPostValidateBeforeCall(emailValidationRequest, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
