/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiCallback;
import com.mailsafepro.ApiClient;
import com.mailsafepro.ApiException;
import com.mailsafepro.ApiResponse;
import com.mailsafepro.Configuration;
import com.mailsafepro.Pair;
import com.mailsafepro.ProgressRequestBody;
import com.mailsafepro.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mailsafepro.model.HTTPValidationError;
import com.mailsafepro.model.JobCreateRequest;
import com.mailsafepro.model.JobCreateResponse;
import com.mailsafepro.model.JobResultsPage;
import com.mailsafepro.model.JobStatusResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JobsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public JobsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public JobsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createJobJobsV1JobsPost
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createJobJobsV1JobsPostCall(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = jobCreateRequest;

        // create path and map variables
        String localVarPath = "/jobs/v1/jobs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xIdempotencyKey != null) {
            localVarHeaderParams.put("X-Idempotency-Key", localVarApiClient.parameterToString(xIdempotencyKey));
        }


        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createJobJobsV1JobsPostValidateBeforeCall(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobCreateRequest' is set
        if (jobCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'jobCreateRequest' when calling createJobJobsV1JobsPost(Async)");
        }

        return createJobJobsV1JobsPostCall(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization, _callback);

    }

    /**
     * Create validation job
     * 
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return JobCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public JobCreateResponse createJobJobsV1JobsPost(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<JobCreateResponse> localVarResp = createJobJobsV1JobsPostWithHttpInfo(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Create validation job
     * 
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;JobCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobCreateResponse> createJobJobsV1JobsPostWithHttpInfo(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = createJobJobsV1JobsPostValidateBeforeCall(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<JobCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create validation job (asynchronously)
     * 
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createJobJobsV1JobsPostAsync(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<JobCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createJobJobsV1JobsPostValidateBeforeCall(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<JobCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createJobJobsV1JobsPost_0
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createJobJobsV1JobsPost_0Call(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = jobCreateRequest;

        // create path and map variables
        String localVarPath = "/jobs/v1/jobs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xIdempotencyKey != null) {
            localVarHeaderParams.put("X-Idempotency-Key", localVarApiClient.parameterToString(xIdempotencyKey));
        }


        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createJobJobsV1JobsPost_0ValidateBeforeCall(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobCreateRequest' is set
        if (jobCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'jobCreateRequest' when calling createJobJobsV1JobsPost_0(Async)");
        }

        return createJobJobsV1JobsPost_0Call(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization, _callback);

    }

    /**
     * Create validation job
     * 
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return JobCreateResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public JobCreateResponse createJobJobsV1JobsPost_0(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<JobCreateResponse> localVarResp = createJobJobsV1JobsPost_0WithHttpInfo(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Create validation job
     * 
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;JobCreateResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobCreateResponse> createJobJobsV1JobsPost_0WithHttpInfo(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = createJobJobsV1JobsPost_0ValidateBeforeCall(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<JobCreateResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create validation job (asynchronously)
     * 
     * @param jobCreateRequest  (required)
     * @param xIdempotencyKey  (optional)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> Job queued </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Idempotent replay </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createJobJobsV1JobsPost_0Async(@javax.annotation.Nonnull JobCreateRequest jobCreateRequest, @javax.annotation.Nullable String xIdempotencyKey, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<JobCreateResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createJobJobsV1JobsPost_0ValidateBeforeCall(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<JobCreateResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getJobResultsJobsV1JobsJobIdResultsGet
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobResultsJobsV1JobsJobIdResultsGetCall(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/v1/jobs/{job_id}/results"
            .replace("{" + "job_id" + "}", localVarApiClient.escapeString(jobId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJobResultsJobsV1JobsJobIdResultsGetValidateBeforeCall(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobId' is set
        if (jobId == null) {
            throw new ApiException("Missing the required parameter 'jobId' when calling getJobResultsJobsV1JobsJobIdResultsGet(Async)");
        }

        return getJobResultsJobsV1JobsJobIdResultsGetCall(jobId, page, size, xAPIKey, authorization, _callback);

    }

    /**
     * Get job results (paged)
     * 
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return JobResultsPage
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public JobResultsPage getJobResultsJobsV1JobsJobIdResultsGet(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<JobResultsPage> localVarResp = getJobResultsJobsV1JobsJobIdResultsGetWithHttpInfo(jobId, page, size, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Get job results (paged)
     * 
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;JobResultsPage&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobResultsPage> getJobResultsJobsV1JobsJobIdResultsGetWithHttpInfo(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getJobResultsJobsV1JobsJobIdResultsGetValidateBeforeCall(jobId, page, size, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<JobResultsPage>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get job results (paged) (asynchronously)
     * 
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobResultsJobsV1JobsJobIdResultsGetAsync(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<JobResultsPage> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJobResultsJobsV1JobsJobIdResultsGetValidateBeforeCall(jobId, page, size, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<JobResultsPage>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getJobResultsJobsV1JobsJobIdResultsGet_0
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobResultsJobsV1JobsJobIdResultsGet_0Call(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/v1/jobs/{job_id}/results"
            .replace("{" + "job_id" + "}", localVarApiClient.escapeString(jobId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJobResultsJobsV1JobsJobIdResultsGet_0ValidateBeforeCall(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobId' is set
        if (jobId == null) {
            throw new ApiException("Missing the required parameter 'jobId' when calling getJobResultsJobsV1JobsJobIdResultsGet_0(Async)");
        }

        return getJobResultsJobsV1JobsJobIdResultsGet_0Call(jobId, page, size, xAPIKey, authorization, _callback);

    }

    /**
     * Get job results (paged)
     * 
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return JobResultsPage
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public JobResultsPage getJobResultsJobsV1JobsJobIdResultsGet_0(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<JobResultsPage> localVarResp = getJobResultsJobsV1JobsJobIdResultsGet_0WithHttpInfo(jobId, page, size, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Get job results (paged)
     * 
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;JobResultsPage&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobResultsPage> getJobResultsJobsV1JobsJobIdResultsGet_0WithHttpInfo(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getJobResultsJobsV1JobsJobIdResultsGet_0ValidateBeforeCall(jobId, page, size, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<JobResultsPage>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get job results (paged) (asynchronously)
     * 
     * @param jobId  (required)
     * @param page  (optional, default to 1)
     * @param size  (optional, default to 500)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobResultsJobsV1JobsJobIdResultsGet_0Async(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer size, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<JobResultsPage> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJobResultsJobsV1JobsJobIdResultsGet_0ValidateBeforeCall(jobId, page, size, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<JobResultsPage>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getJobStatusJobsV1JobsJobIdGet
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobStatusJobsV1JobsJobIdGetCall(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/v1/jobs/{job_id}"
            .replace("{" + "job_id" + "}", localVarApiClient.escapeString(jobId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJobStatusJobsV1JobsJobIdGetValidateBeforeCall(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobId' is set
        if (jobId == null) {
            throw new ApiException("Missing the required parameter 'jobId' when calling getJobStatusJobsV1JobsJobIdGet(Async)");
        }

        return getJobStatusJobsV1JobsJobIdGetCall(jobId, xAPIKey, authorization, _callback);

    }

    /**
     * Get job status
     * 
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return JobStatusResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public JobStatusResponse getJobStatusJobsV1JobsJobIdGet(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<JobStatusResponse> localVarResp = getJobStatusJobsV1JobsJobIdGetWithHttpInfo(jobId, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Get job status
     * 
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;JobStatusResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobStatusResponse> getJobStatusJobsV1JobsJobIdGetWithHttpInfo(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getJobStatusJobsV1JobsJobIdGetValidateBeforeCall(jobId, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<JobStatusResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get job status (asynchronously)
     * 
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobStatusJobsV1JobsJobIdGetAsync(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<JobStatusResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJobStatusJobsV1JobsJobIdGetValidateBeforeCall(jobId, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<JobStatusResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getJobStatusJobsV1JobsJobIdGet_0
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobStatusJobsV1JobsJobIdGet_0Call(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/v1/jobs/{job_id}"
            .replace("{" + "job_id" + "}", localVarApiClient.escapeString(jobId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAPIKey != null) {
            localVarHeaderParams.put("X-API-Key", localVarApiClient.parameterToString(xAPIKey));
        }


        if (authorization != null) {
            localVarHeaderParams.put("authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJobStatusJobsV1JobsJobIdGet_0ValidateBeforeCall(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobId' is set
        if (jobId == null) {
            throw new ApiException("Missing the required parameter 'jobId' when calling getJobStatusJobsV1JobsJobIdGet_0(Async)");
        }

        return getJobStatusJobsV1JobsJobIdGet_0Call(jobId, xAPIKey, authorization, _callback);

    }

    /**
     * Get job status
     * 
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return JobStatusResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public JobStatusResponse getJobStatusJobsV1JobsJobIdGet_0(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        ApiResponse<JobStatusResponse> localVarResp = getJobStatusJobsV1JobsJobIdGet_0WithHttpInfo(jobId, xAPIKey, authorization);
        return localVarResp.getData();
    }

    /**
     * Get job status
     * 
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @return ApiResponse&lt;JobStatusResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobStatusResponse> getJobStatusJobsV1JobsJobIdGet_0WithHttpInfo(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization) throws ApiException {
        okhttp3.Call localVarCall = getJobStatusJobsV1JobsJobIdGet_0ValidateBeforeCall(jobId, xAPIKey, authorization, null);
        Type localVarReturnType = new TypeToken<JobStatusResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get job status (asynchronously)
     * 
     * @param jobId  (required)
     * @param xAPIKey  (optional)
     * @param authorization  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobStatusJobsV1JobsJobIdGet_0Async(@javax.annotation.Nonnull String jobId, @javax.annotation.Nullable String xAPIKey, @javax.annotation.Nullable String authorization, final ApiCallback<JobStatusResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJobStatusJobsV1JobsJobIdGet_0ValidateBeforeCall(jobId, xAPIKey, authorization, _callback);
        Type localVarReturnType = new TypeToken<JobStatusResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
