/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiCallback;
import com.mailsafepro.ApiClient;
import com.mailsafepro.ApiException;
import com.mailsafepro.ApiResponse;
import com.mailsafepro.Configuration;
import com.mailsafepro.Pair;
import com.mailsafepro.ProgressRequestBody;
import com.mailsafepro.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.mailsafepro.model.HTTPValidationError;
import java.time.OffsetDateTime;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LogsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LogsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LogsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for clearRequestLogsLogsLogsRequestsDelete
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call clearRequestLogsLogsLogsRequestsDeleteCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/logs/logs/requests";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call clearRequestLogsLogsLogsRequestsDeleteValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return clearRequestLogsLogsLogsRequestsDeleteCall(_callback);

    }

    /**
     * Clear Request Logs
     * Clear all request logs for current user.
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public Object clearRequestLogsLogsLogsRequestsDelete() throws ApiException {
        ApiResponse<Object> localVarResp = clearRequestLogsLogsLogsRequestsDeleteWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Clear Request Logs
     * Clear all request logs for current user.
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> clearRequestLogsLogsLogsRequestsDeleteWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = clearRequestLogsLogsLogsRequestsDeleteValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Clear Request Logs (asynchronously)
     * Clear all request logs for current user.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call clearRequestLogsLogsLogsRequestsDeleteAsync(final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = clearRequestLogsLogsLogsRequestsDeleteValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRequestLogsLogsLogsRequestsGet
     * @param limit Max results to return (optional, default to 100)
     * @param statusCode Filter by HTTP status code (optional)
     * @param endpoint Filter by endpoint path (optional)
     * @param method Filter by HTTP method (GET, POST, etc) (optional)
     * @param since Filter by timestamp (ISO 8601) (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRequestLogsLogsLogsRequestsGetCall(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer statusCode, @javax.annotation.Nullable String endpoint, @javax.annotation.Nullable String method, @javax.annotation.Nullable OffsetDateTime since, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/logs/logs/requests";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (statusCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status_code", statusCode));
        }

        if (endpoint != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("endpoint", endpoint));
        }

        if (method != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("method", method));
        }

        if (since != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("since", since));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRequestLogsLogsLogsRequestsGetValidateBeforeCall(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer statusCode, @javax.annotation.Nullable String endpoint, @javax.annotation.Nullable String method, @javax.annotation.Nullable OffsetDateTime since, final ApiCallback _callback) throws ApiException {
        return getRequestLogsLogsLogsRequestsGetCall(limit, statusCode, endpoint, method, since, _callback);

    }

    /**
     * Get Request Logs
     * Get request logs for authenticated user.
     * @param limit Max results to return (optional, default to 100)
     * @param statusCode Filter by HTTP status code (optional)
     * @param endpoint Filter by endpoint path (optional)
     * @param method Filter by HTTP method (GET, POST, etc) (optional)
     * @param since Filter by timestamp (ISO 8601) (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object getRequestLogsLogsLogsRequestsGet(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer statusCode, @javax.annotation.Nullable String endpoint, @javax.annotation.Nullable String method, @javax.annotation.Nullable OffsetDateTime since) throws ApiException {
        ApiResponse<Object> localVarResp = getRequestLogsLogsLogsRequestsGetWithHttpInfo(limit, statusCode, endpoint, method, since);
        return localVarResp.getData();
    }

    /**
     * Get Request Logs
     * Get request logs for authenticated user.
     * @param limit Max results to return (optional, default to 100)
     * @param statusCode Filter by HTTP status code (optional)
     * @param endpoint Filter by endpoint path (optional)
     * @param method Filter by HTTP method (GET, POST, etc) (optional)
     * @param since Filter by timestamp (ISO 8601) (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> getRequestLogsLogsLogsRequestsGetWithHttpInfo(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer statusCode, @javax.annotation.Nullable String endpoint, @javax.annotation.Nullable String method, @javax.annotation.Nullable OffsetDateTime since) throws ApiException {
        okhttp3.Call localVarCall = getRequestLogsLogsLogsRequestsGetValidateBeforeCall(limit, statusCode, endpoint, method, since, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Request Logs (asynchronously)
     * Get request logs for authenticated user.
     * @param limit Max results to return (optional, default to 100)
     * @param statusCode Filter by HTTP status code (optional)
     * @param endpoint Filter by endpoint path (optional)
     * @param method Filter by HTTP method (GET, POST, etc) (optional)
     * @param since Filter by timestamp (ISO 8601) (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRequestLogsLogsLogsRequestsGetAsync(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer statusCode, @javax.annotation.Nullable String endpoint, @javax.annotation.Nullable String method, @javax.annotation.Nullable OffsetDateTime since, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRequestLogsLogsLogsRequestsGetValidateBeforeCall(limit, statusCode, endpoint, method, since, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
