/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailsafepro.model.EmailResponse;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * Batch validation response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class BatchEmailResponse {
  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  @javax.annotation.Nonnull
  private Integer count;

  public static final String SERIALIZED_NAME_VALID_COUNT = "valid_count";
  @SerializedName(SERIALIZED_NAME_VALID_COUNT)
  @javax.annotation.Nonnull
  private Integer validCount;

  public static final String SERIALIZED_NAME_INVALID_COUNT = "invalid_count";
  @SerializedName(SERIALIZED_NAME_INVALID_COUNT)
  @javax.annotation.Nonnull
  private Integer invalidCount;

  public static final String SERIALIZED_NAME_PROCESSING_TIME = "processing_time";
  @SerializedName(SERIALIZED_NAME_PROCESSING_TIME)
  @javax.annotation.Nonnull
  private BigDecimal processingTime;

  public static final String SERIALIZED_NAME_AVERAGE_TIME = "average_time";
  @SerializedName(SERIALIZED_NAME_AVERAGE_TIME)
  @javax.annotation.Nonnull
  private BigDecimal averageTime;

  public static final String SERIALIZED_NAME_RESULTS = "results";
  @SerializedName(SERIALIZED_NAME_RESULTS)
  @javax.annotation.Nonnull
  private List<EmailResponse> results = new ArrayList<>();

  public BatchEmailResponse() {
  }

  public BatchEmailResponse count(@javax.annotation.Nonnull Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Total emails processed
   * minimum: 0
   * @return count
   */
  @javax.annotation.Nonnull
  public Integer getCount() {
    return count;
  }

  public void setCount(@javax.annotation.Nonnull Integer count) {
    this.count = count;
  }


  public BatchEmailResponse validCount(@javax.annotation.Nonnull Integer validCount) {
    this.validCount = validCount;
    return this;
  }

  /**
   * Number of valid emails
   * minimum: 0
   * @return validCount
   */
  @javax.annotation.Nonnull
  public Integer getValidCount() {
    return validCount;
  }

  public void setValidCount(@javax.annotation.Nonnull Integer validCount) {
    this.validCount = validCount;
  }


  public BatchEmailResponse invalidCount(@javax.annotation.Nonnull Integer invalidCount) {
    this.invalidCount = invalidCount;
    return this;
  }

  /**
   * Number of invalid emails
   * minimum: 0
   * @return invalidCount
   */
  @javax.annotation.Nonnull
  public Integer getInvalidCount() {
    return invalidCount;
  }

  public void setInvalidCount(@javax.annotation.Nonnull Integer invalidCount) {
    this.invalidCount = invalidCount;
  }


  public BatchEmailResponse processingTime(@javax.annotation.Nonnull BigDecimal processingTime) {
    this.processingTime = processingTime;
    return this;
  }

  /**
   * Total processing time in seconds
   * minimum: 0.0
   * @return processingTime
   */
  @javax.annotation.Nonnull
  public BigDecimal getProcessingTime() {
    return processingTime;
  }

  public void setProcessingTime(@javax.annotation.Nonnull BigDecimal processingTime) {
    this.processingTime = processingTime;
  }


  public BatchEmailResponse averageTime(@javax.annotation.Nonnull BigDecimal averageTime) {
    this.averageTime = averageTime;
    return this;
  }

  /**
   * Average processing time per email
   * minimum: 0.0
   * @return averageTime
   */
  @javax.annotation.Nonnull
  public BigDecimal getAverageTime() {
    return averageTime;
  }

  public void setAverageTime(@javax.annotation.Nonnull BigDecimal averageTime) {
    this.averageTime = averageTime;
  }


  public BatchEmailResponse results(@javax.annotation.Nonnull List<EmailResponse> results) {
    this.results = results;
    return this;
  }

  public BatchEmailResponse addResultsItem(EmailResponse resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Individual validation results
   * @return results
   */
  @javax.annotation.Nonnull
  public List<EmailResponse> getResults() {
    return results;
  }

  public void setResults(@javax.annotation.Nonnull List<EmailResponse> results) {
    this.results = results;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchEmailResponse batchEmailResponse = (BatchEmailResponse) o;
    return Objects.equals(this.count, batchEmailResponse.count) &&
        Objects.equals(this.validCount, batchEmailResponse.validCount) &&
        Objects.equals(this.invalidCount, batchEmailResponse.invalidCount) &&
        Objects.equals(this.processingTime, batchEmailResponse.processingTime) &&
        Objects.equals(this.averageTime, batchEmailResponse.averageTime) &&
        Objects.equals(this.results, batchEmailResponse.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, validCount, invalidCount, processingTime, averageTime, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchEmailResponse {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    validCount: ").append(toIndentedString(validCount)).append("\n");
    sb.append("    invalidCount: ").append(toIndentedString(invalidCount)).append("\n");
    sb.append("    processingTime: ").append(toIndentedString(processingTime)).append("\n");
    sb.append("    averageTime: ").append(toIndentedString(averageTime)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("count", "valid_count", "invalid_count", "processing_time", "average_time", "results"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("count", "valid_count", "invalid_count", "processing_time", "average_time", "results"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchEmailResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchEmailResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BatchEmailResponse is not found in the empty JSON string", BatchEmailResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchEmailResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BatchEmailResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchEmailResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("results").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `results` to be an array in the JSON string but got `%s`", jsonObj.get("results").toString()));
      }

      JsonArray jsonArrayresults = jsonObj.getAsJsonArray("results");
      // validate the required field `results` (array)
      for (int i = 0; i < jsonArrayresults.size(); i++) {
        EmailResponse.validateJsonElement(jsonArrayresults.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchEmailResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchEmailResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchEmailResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchEmailResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchEmailResponse>() {
           @Override
           public void write(JsonWriter out, BatchEmailResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchEmailResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchEmailResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchEmailResponse
   * @throws IOException if the JSON string is invalid with respect to BatchEmailResponse
   */
  public static BatchEmailResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchEmailResponse.class);
  }

  /**
   * Convert an instance of BatchEmailResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

