/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mailsafepro.model.PriorityEnum;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * Request model for single email validation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class EmailValidationRequest {
  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nonnull
  private String email;

  public static final String SERIALIZED_NAME_CHECK_SMTP = "check_smtp";
  @SerializedName(SERIALIZED_NAME_CHECK_SMTP)
  @javax.annotation.Nullable
  private Boolean checkSmtp = false;

  public static final String SERIALIZED_NAME_INCLUDE_RAW_DNS = "include_raw_dns";
  @SerializedName(SERIALIZED_NAME_INCLUDE_RAW_DNS)
  @javax.annotation.Nullable
  private Boolean includeRawDns = false;

  public static final String SERIALIZED_NAME_TESTING_MODE = "testing_mode";
  @SerializedName(SERIALIZED_NAME_TESTING_MODE)
  @javax.annotation.Nullable
  private Boolean testingMode = false;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nullable
  private PriorityEnum priority = PriorityEnum.STANDARD;

  public EmailValidationRequest() {
  }

  public EmailValidationRequest email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * Email address to validate (RFC 5321 compliant)
   * @return email
   */
  @javax.annotation.Nonnull
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public EmailValidationRequest checkSmtp(@javax.annotation.Nullable Boolean checkSmtp) {
    this.checkSmtp = checkSmtp;
    return this;
  }

  /**
   * Enable SMTP mailbox verification
   * @return checkSmtp
   */
  @javax.annotation.Nullable
  public Boolean getCheckSmtp() {
    return checkSmtp;
  }

  public void setCheckSmtp(@javax.annotation.Nullable Boolean checkSmtp) {
    this.checkSmtp = checkSmtp;
  }


  public EmailValidationRequest includeRawDns(@javax.annotation.Nullable Boolean includeRawDns) {
    this.includeRawDns = includeRawDns;
    return this;
  }

  /**
   * Include raw DNS records
   * @return includeRawDns
   */
  @javax.annotation.Nullable
  public Boolean getIncludeRawDns() {
    return includeRawDns;
  }

  public void setIncludeRawDns(@javax.annotation.Nullable Boolean includeRawDns) {
    this.includeRawDns = includeRawDns;
  }


  public EmailValidationRequest testingMode(@javax.annotation.Nullable Boolean testingMode) {
    this.testingMode = testingMode;
    return this;
  }

  /**
   * Enable testing mode (allows special TLDs like .test, .example, etc.)
   * @return testingMode
   */
  @javax.annotation.Nullable
  public Boolean getTestingMode() {
    return testingMode;
  }

  public void setTestingMode(@javax.annotation.Nullable Boolean testingMode) {
    this.testingMode = testingMode;
  }


  public EmailValidationRequest priority(@javax.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Validation priority level
   * @return priority
   */
  @javax.annotation.Nullable
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(@javax.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailValidationRequest emailValidationRequest = (EmailValidationRequest) o;
    return Objects.equals(this.email, emailValidationRequest.email) &&
        Objects.equals(this.checkSmtp, emailValidationRequest.checkSmtp) &&
        Objects.equals(this.includeRawDns, emailValidationRequest.includeRawDns) &&
        Objects.equals(this.testingMode, emailValidationRequest.testingMode) &&
        Objects.equals(this.priority, emailValidationRequest.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, checkSmtp, includeRawDns, testingMode, priority);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailValidationRequest {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    checkSmtp: ").append(toIndentedString(checkSmtp)).append("\n");
    sb.append("    includeRawDns: ").append(toIndentedString(includeRawDns)).append("\n");
    sb.append("    testingMode: ").append(toIndentedString(testingMode)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("email", "check_smtp", "include_raw_dns", "testing_mode", "priority"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("email"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EmailValidationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EmailValidationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EmailValidationRequest is not found in the empty JSON string", EmailValidationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EmailValidationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EmailValidationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EmailValidationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      // validate the optional field `priority`
      if (jsonObj.get("priority") != null && !jsonObj.get("priority").isJsonNull()) {
        PriorityEnum.validateJsonElement(jsonObj.get("priority"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmailValidationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmailValidationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmailValidationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmailValidationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<EmailValidationRequest>() {
           @Override
           public void write(JsonWriter out, EmailValidationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmailValidationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EmailValidationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EmailValidationRequest
   * @throws IOException if the JSON string is invalid with respect to EmailValidationRequest
   */
  public static EmailValidationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmailValidationRequest.class);
  }

  /**
   * Convert an instance of EmailValidationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

