/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RiskLevelEnum
 */
@JsonAdapter(RiskLevelEnum.Adapter.class)
public enum RiskLevelEnum {
  
  LOW("low"),
  
  MEDIUM("medium"),
  
  HIGH("high"),
  
  UNKNOWN("unknown");

  private String value;

  RiskLevelEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RiskLevelEnum fromValue(String value) {
    for (RiskLevelEnum b : RiskLevelEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RiskLevelEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final RiskLevelEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RiskLevelEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RiskLevelEnum.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RiskLevelEnum.fromValue(value);
  }
}

