/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mailsafepro.JSON;

/**
 * SMTP verification results
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-03T13:28:40.088014+01:00[Europe/Madrid]", comments = "Generator version: 7.18.0")
public class SMTPInfo {
  public static final String SERIALIZED_NAME_CHECKED = "checked";
  @SerializedName(SERIALIZED_NAME_CHECKED)
  @javax.annotation.Nonnull
  private Boolean checked;

  public static final String SERIALIZED_NAME_MAILBOX_EXISTS = "mailbox_exists";
  @SerializedName(SERIALIZED_NAME_MAILBOX_EXISTS)
  @javax.annotation.Nullable
  private Boolean mailboxExists;

  public static final String SERIALIZED_NAME_MX_SERVER = "mx_server";
  @SerializedName(SERIALIZED_NAME_MX_SERVER)
  @javax.annotation.Nullable
  private String mxServer;

  public static final String SERIALIZED_NAME_RESPONSE_TIME = "response_time";
  @SerializedName(SERIALIZED_NAME_RESPONSE_TIME)
  @javax.annotation.Nullable
  private BigDecimal responseTime;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "error_message";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  @javax.annotation.Nullable
  private String errorMessage;

  public SMTPInfo() {
  }

  public SMTPInfo checked(@javax.annotation.Nonnull Boolean checked) {
    this.checked = checked;
    return this;
  }

  /**
   * SMTP check was performed
   * @return checked
   */
  @javax.annotation.Nonnull
  public Boolean getChecked() {
    return checked;
  }

  public void setChecked(@javax.annotation.Nonnull Boolean checked) {
    this.checked = checked;
  }


  public SMTPInfo mailboxExists(@javax.annotation.Nullable Boolean mailboxExists) {
    this.mailboxExists = mailboxExists;
    return this;
  }

  /**
   * Get mailboxExists
   * @return mailboxExists
   */
  @javax.annotation.Nullable
  public Boolean getMailboxExists() {
    return mailboxExists;
  }

  public void setMailboxExists(@javax.annotation.Nullable Boolean mailboxExists) {
    this.mailboxExists = mailboxExists;
  }


  public SMTPInfo mxServer(@javax.annotation.Nullable String mxServer) {
    this.mxServer = mxServer;
    return this;
  }

  /**
   * Get mxServer
   * @return mxServer
   */
  @javax.annotation.Nullable
  public String getMxServer() {
    return mxServer;
  }

  public void setMxServer(@javax.annotation.Nullable String mxServer) {
    this.mxServer = mxServer;
  }


  public SMTPInfo responseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = responseTime;
    return this;
  }

  /**
   * Get responseTime
   * @return responseTime
   */
  @javax.annotation.Nullable
  public BigDecimal getResponseTime() {
    return responseTime;
  }

  public void setResponseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = responseTime;
  }


  public SMTPInfo errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Get errorMessage
   * @return errorMessage
   */
  @javax.annotation.Nullable
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SMTPInfo smTPInfo = (SMTPInfo) o;
    return Objects.equals(this.checked, smTPInfo.checked) &&
        Objects.equals(this.mailboxExists, smTPInfo.mailboxExists) &&
        Objects.equals(this.mxServer, smTPInfo.mxServer) &&
        Objects.equals(this.responseTime, smTPInfo.responseTime) &&
        Objects.equals(this.errorMessage, smTPInfo.errorMessage);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(checked, mailboxExists, mxServer, responseTime, errorMessage);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SMTPInfo {\n");
    sb.append("    checked: ").append(toIndentedString(checked)).append("\n");
    sb.append("    mailboxExists: ").append(toIndentedString(mailboxExists)).append("\n");
    sb.append("    mxServer: ").append(toIndentedString(mxServer)).append("\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("checked", "mailbox_exists", "mx_server", "response_time", "error_message"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("checked"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SMTPInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SMTPInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SMTPInfo is not found in the empty JSON string", SMTPInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SMTPInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SMTPInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SMTPInfo.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("mx_server") != null && !jsonObj.get("mx_server").isJsonNull()) && !jsonObj.get("mx_server").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mx_server` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mx_server").toString()));
      }
      if ((jsonObj.get("error_message") != null && !jsonObj.get("error_message").isJsonNull()) && !jsonObj.get("error_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error_message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SMTPInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SMTPInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SMTPInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SMTPInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<SMTPInfo>() {
           @Override
           public void write(JsonWriter out, SMTPInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SMTPInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SMTPInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SMTPInfo
   * @throws IOException if the JSON string is invalid with respect to SMTPInfo
   */
  public static SMTPInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SMTPInfo.class);
  }

  /**
   * Convert an instance of SMTPInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

