/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiException;
import com.mailsafepro.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Ask Gemini
     *
     * Llama a Gemini para generar texto a partir de un prompt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void askGeminiGeminiGetTest() throws ApiException {
        String prompt = null;
        Object response = api.askGeminiGeminiGet(prompt);
        // TODO: test validations
    }

    /**
     * Run Audit
     *
     * Lanza auditoría en path (ruta absoluta o relativa a la raíz del proyecto). Header obligatorio: X-Audit-Token: &lt;AUDIT_SECRET&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void runAuditAdminAuditProjectPostTest() throws ApiException {
        String path = null;
        String xAuditToken = null;
        Object response = api.runAuditAdminAuditProjectPost(path, xAuditToken);
        // TODO: test validations
    }

}
