/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiException;
import com.mailsafepro.model.HTTPValidationError;
import com.mailsafepro.model.WebhookCreate;
import com.mailsafepro.model.WebhookUpdate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhooksManagementApi
 */
@Disabled
public class WebhooksManagementApiTest {

    private final WebhooksManagementApi api = new WebhooksManagementApi();

    /**
     * Create Webhook
     *
     * Create a new webhook endpoint.  Events available: - validation.completed: Single email validation finished - batch.completed: Batch validation finished - usage.limit_reached: API usage limit reached (80%)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWebhookWebhooksManagementWebhooksPostTest() throws ApiException {
        WebhookCreate webhookCreate = null;
        Object response = api.createWebhookWebhooksManagementWebhooksPost(webhookCreate);
        // TODO: test validations
    }

    /**
     * Delete Webhook
     *
     * Delete webhook.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteWebhookWebhooksManagementWebhooksWebhookIdDeleteTest() throws ApiException {
        String webhookId = null;
        Object response = api.deleteWebhookWebhooksManagementWebhooksWebhookIdDelete(webhookId);
        // TODO: test validations
    }

    /**
     * Get Deliveries
     *
     * Get delivery history for webhook.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDeliveriesWebhooksManagementWebhooksWebhookIdDeliveriesGetTest() throws ApiException {
        String webhookId = null;
        Integer limit = null;
        Object response = api.getDeliveriesWebhooksManagementWebhooksWebhookIdDeliveriesGet(webhookId, limit);
        // TODO: test validations
    }

    /**
     * Get Webhook
     *
     * Get webhook details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWebhookWebhooksManagementWebhooksWebhookIdGetTest() throws ApiException {
        String webhookId = null;
        Object response = api.getWebhookWebhooksManagementWebhooksWebhookIdGet(webhookId);
        // TODO: test validations
    }

    /**
     * List Webhooks
     *
     * List all webhooks for authenticated user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listWebhooksWebhooksManagementWebhooksGetTest() throws ApiException {
        Object response = api.listWebhooksWebhooksManagementWebhooksGet();
        // TODO: test validations
    }

    /**
     * Test Webhook
     *
     * Send test event to webhook.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void testWebhookWebhooksManagementWebhooksWebhookIdTestPostTest() throws ApiException {
        String webhookId = null;
        Object response = api.testWebhookWebhooksManagementWebhooksWebhookIdTestPost(webhookId);
        // TODO: test validations
    }

    /**
     * Update Webhook
     *
     * Update webhook configuration.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateWebhookWebhooksManagementWebhooksWebhookIdPatchTest() throws ApiException {
        String webhookId = null;
        WebhookUpdate webhookUpdate = null;
        Object response = api.updateWebhookWebhooksManagementWebhooksWebhookIdPatch(webhookId, webhookUpdate);
        // TODO: test validations
    }

}
