/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiException;
import com.mailsafepro.model.HTTPValidationError;
import com.mailsafepro.model.JobCreateRequest;
import com.mailsafepro.model.JobCreateResponse;
import com.mailsafepro.model.JobResultsPage;
import com.mailsafepro.model.JobStatusResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobsApi
 */
@Disabled
public class JobsApiTest {

    private final JobsApi api = new JobsApi();

    /**
     * Create validation job
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createJobJobsV1JobsPostTest() throws ApiException {
        JobCreateRequest jobCreateRequest = null;
        String xIdempotencyKey = null;
        String xAPIKey = null;
        String authorization = null;
        JobCreateResponse response = api.createJobJobsV1JobsPost(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization);
        // TODO: test validations
    }

    /**
     * Create validation job
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createJobJobsV1JobsPost_0Test() throws ApiException {
        JobCreateRequest jobCreateRequest = null;
        String xIdempotencyKey = null;
        String xAPIKey = null;
        String authorization = null;
        JobCreateResponse response = api.createJobJobsV1JobsPost_0(jobCreateRequest, xIdempotencyKey, xAPIKey, authorization);
        // TODO: test validations
    }

    /**
     * Get job results (paged)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobResultsJobsV1JobsJobIdResultsGetTest() throws ApiException {
        String jobId = null;
        Integer page = null;
        Integer size = null;
        String xAPIKey = null;
        String authorization = null;
        JobResultsPage response = api.getJobResultsJobsV1JobsJobIdResultsGet(jobId, page, size, xAPIKey, authorization);
        // TODO: test validations
    }

    /**
     * Get job results (paged)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobResultsJobsV1JobsJobIdResultsGet_0Test() throws ApiException {
        String jobId = null;
        Integer page = null;
        Integer size = null;
        String xAPIKey = null;
        String authorization = null;
        JobResultsPage response = api.getJobResultsJobsV1JobsJobIdResultsGet_0(jobId, page, size, xAPIKey, authorization);
        // TODO: test validations
    }

    /**
     * Get job status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobStatusJobsV1JobsJobIdGetTest() throws ApiException {
        String jobId = null;
        String xAPIKey = null;
        String authorization = null;
        JobStatusResponse response = api.getJobStatusJobsV1JobsJobIdGet(jobId, xAPIKey, authorization);
        // TODO: test validations
    }

    /**
     * Get job status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobStatusJobsV1JobsJobIdGet_0Test() throws ApiException {
        String jobId = null;
        String xAPIKey = null;
        String authorization = null;
        JobStatusResponse response = api.getJobStatusJobsV1JobsJobIdGet_0(jobId, xAPIKey, authorization);
        // TODO: test validations
    }

}
