/*
 * Email Validation API — Enterprise-grade Email Verification
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mailsafepro.api;

import com.mailsafepro.ApiException;
import com.mailsafepro.model.HTTPValidationError;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogsApi
 */
@Disabled
public class LogsApiTest {

    private final LogsApi api = new LogsApi();

    /**
     * Clear Request Logs
     *
     * Clear all request logs for current user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void clearRequestLogsLogsLogsRequestsDeleteTest() throws ApiException {
        Object response = api.clearRequestLogsLogsLogsRequestsDelete();
        // TODO: test validations
    }

    /**
     * Get Request Logs
     *
     * Get request logs for authenticated user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRequestLogsLogsLogsRequestsGetTest() throws ApiException {
        Integer limit = null;
        Integer statusCode = null;
        String endpoint = null;
        String method = null;
        OffsetDateTime since = null;
        Object response = api.getRequestLogsLogsLogsRequestsGet(limit, statusCode, endpoint, method, since);
        // TODO: test validations
    }

}
